// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/repository.go -destination=mocks/repo_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
